// ── Constantes métier ─────────────────────────────────────────────────────
export const ACADEMIC_YEARS = Array.from({length: 10}, (_, i) => {
  const y = 2025 + i
  return `${y}/${y+1}`
})

export const SEMESTERS = ACADEMIC_YEARS.flatMap(y => [
  `S1 — ${y}`, `S2 — ${y}`
])

export const GSMI_AXES = [
  'Geology & Exploration',
  'Mine & Mineral Processing (MMP)',
  'Sustainable Mining & Environment (SME)',
]

export const GRADES = [
  'Assistant Professor',
  'Associate Professor',
  'Full Professor',
  'Professeur Invité',
  'Visiting Professor',
]

export const INTEGRATION_YEARS = Array.from({length: 20}, (_, i) => `${2005 + i}`)

// ── Sections du formulaire ────────────────────────────────────────────────
// MODE : 'prevision' | 'revision_s1' | 'bilan_annuel'
// Chaque champ peut avoir : validate(value) → string|null

export function getSections(mode = 'prevision', lang = 'fr') {
  const T = TRANSLATIONS[lang]

  return [
    // ── SECTION 0 : IDENTIFICATION ─────────────────────────────────────
    {
      id: 'identification',
      title: T.s_identification,
      icon: '👤',
      color: '#0D1B2A',
      fields: [
        { id: 'nom',           label: T.f_nom,          type: 'text',   required: true,  placeholder: 'Prénom NOM' },
        { id: 'email',         label: T.f_email,        type: 'email',  required: true,  placeholder: 'prenom.nom@um6p.ma',
          validate: v => v && !v.includes('@') ? T.err_email : null },
        { id: 'grade',         label: T.f_grade,        type: 'select', required: true,  options: GRADES },
        { id: 'axe_recherche', label: T.f_axe,          type: 'select', required: true,  options: GSMI_AXES },
        { id: 'annee_integ',   label: T.f_annee_integ,  type: 'select', required: true,  options: INTEGRATION_YEARS },
        { id: 'orcid',         label: T.f_orcid,        type: 'text',   required: false, placeholder: '0000-0000-0000-0000',
          hint: T.hint_orcid,
          validate: v => v && !/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/.test(v) ? T.err_orcid : null },
        { id: 'scopus_url',    label: T.f_scopus,       type: 'url',    required: false, placeholder: 'https://www.scopus.com/authid/...' },
        {
          id: 'annee_academique', label: T.f_annee_acad, type: 'select', required: true,
          options: ACADEMIC_YEARS,
          hint: T.hint_annee_acad,
        },
        ...(mode !== 'prevision' ? [{
          id: 'semestre_saisi', label: T.f_semestre, type: 'select', required: true,
          options: mode === 'revision_s1' ? ['S1'] : ['S1', 'S2', 'Bilan annuel'],
        }] : []),
      ],
    },

    // ── SECTION 1 : OBJECTIFS / PRÉVISIONS ────────────────────────────
    ...(mode === 'prevision' ? [{
      id: 'previsions',
      title: T.s_previsions,
      icon: '🎯',
      color: '#1A56DB',
      hint: T.hint_previsions,
      fields: [
        { id: 'prev_pub_total',    label: T.f_prev_pub,       type: 'number', required: true,  min: 0, max: 50 },
        { id: 'prev_pub_q1q2',     label: T.f_prev_q1q2,      type: 'number', required: true,  min: 0, max: 50,
          validate: (v, form) => +v > +(form.prev_pub_total||0) ? T.err_q1q2_gt_total : null },
        { id: 'prev_citations',    label: T.f_prev_citations,  type: 'number', required: false, min: 0 },
        { id: 'prev_projets_obt',  label: T.f_prev_projets,   type: 'number', required: true,  min: 0 },
        { id: 'prev_budget',       label: T.f_prev_budget,    type: 'number', required: false, min: 0, hint: T.hint_mad },
        { id: 'prev_conf_int',     label: T.f_prev_conf,      type: 'number', required: false, min: 0 },
        { id: 'prev_brevets',      label: T.f_prev_brevets,   type: 'number', required: false, min: 0 },
        { id: 'prev_h_init',       label: T.f_prev_h_init,    type: 'number', required: true,  min: 0 },
        { id: 'prev_h_exec',       label: T.f_prev_h_exec,    type: 'number', required: false, min: 0 },
        { id: 'prev_h_doct',       label: T.f_prev_h_doct,    type: 'number', required: false, min: 0 },
        { id: 'prev_doctorants',   label: T.f_prev_doct,      type: 'number', required: true,  min: 0 },
        { id: 'prev_pfe',          label: T.f_prev_pfe,       type: 'number', required: false, min: 0 },
        { id: 'prev_prestations',  label: T.f_prev_prest,     type: 'number', required: false, min: 0 },
        { id: 'prev_revenus',      label: T.f_prev_revenus,   type: 'number', required: false, min: 0, hint: T.hint_mad },
        { id: 'objectifs_texte',   label: T.f_objectifs_txt,  type: 'textarea', required: false,
          placeholder: T.ph_objectifs },
      ],
    }] : []),

    // ── SECTION 2 : PRODUCTION SCIENTIFIQUE ───────────────────────────
    {
      id: 'production',
      title: T.s_production,
      icon: '🔬',
      color: '#047481',
      fields: [
        { id: 'pub_soumises',   label: T.f_pub_soumises,   type: 'number', required: true,  min: 0,
          hint: T.hint_pub_soumises },
        { id: 'pub_acceptees',  label: T.f_pub_acceptees,  type: 'number', required: true,  min: 0,
          validate: (v, form) => +v > +(form.pub_soumises||999) ? T.err_acc_gt_soum : null },
        { id: 'pub_q1q2',       label: T.f_pub_q1q2,       type: 'number', required: false, min: 0,
          validate: (v, form) => +v > +(form.pub_acceptees||999) ? T.err_q1q2_gt_acc : null },
        { id: 'pub_final',      label: T.f_pub_final,      type: 'number', required: false, min: 0 },
        { id: 'citations',      label: T.f_citations,      type: 'number', required: false, min: 0 },
        { id: 'open_access',    label: T.f_open_access,    type: 'number', required: false, min: 0,
          validate: (v, form) => +v > +(form.pub_acceptees||999) ? T.err_oa_gt_acc : null },
        { id: 'type_oa',        label: T.f_type_oa,        type: 'select', required: false,
          options: ['Aucun', 'Gold Open Access', 'Green Open Access', 'Hybrid Gold', 'Diamond OA'] },
        { id: 'livres',         label: T.f_livres,         type: 'number', required: false, min: 0 },
        {
          id: 'doi_list',
          label: T.f_doi_list,
          type: 'doi_field',
          required: false,
          hint: T.hint_doi,
        },
        {
          id: 'refs_biblio',
          label: T.f_refs,
          type: 'textarea',
          required: false,
          placeholder: T.ph_refs,
          hint: T.hint_refs,
        },
      ],
    },

    // ── SECTION 3 : PROJETS & RAYONNEMENT ────────────────────────────
    {
      id: 'projets',
      title: T.s_projets,
      icon: '💰',
      color: '#057A55',
      fields: [
        { id: 'projets_soumis',   label: T.f_proj_soumis,   type: 'number', required: true,  min: 0 },
        { id: 'projets_obtenus',  label: T.f_proj_obtenus,  type: 'number', required: true,  min: 0,
          validate: (v, form) => +v > +(form.projets_soumis||999) ? T.err_proj_gt_soum : null },
        { id: 'budget_mad',       label: T.f_budget,        type: 'number', required: false, min: 0, hint: T.hint_mad },
        { id: 'projets_internat', label: T.f_proj_internat, type: 'number', required: false, min: 0,
          validate: (v, form) => +v > +(form.projets_obtenus||999) ? T.err_internat_gt_obt : null },
        { id: 'financement',      label: T.f_financement,   type: 'select', required: false,
          options: ['Aucun', 'National (CNRST, OCP…)', 'International (EU, World Bank…)', 'Industriel', 'Institutionnel UM6P', 'Bilatéral'] },
        { id: 'role_projet',      label: T.f_role_projet,   type: 'select', required: false,
          options: ['PI (Principal Investigator)', 'Co-PI', 'Participant', 'Coordinateur', 'Consultant'] },
        { id: 'conferences_int',  label: T.f_conf_int,      type: 'number', required: false, min: 0 },
        { id: 'comm_invitees',    label: T.f_comm_inv,      type: 'number', required: false, min: 0 },
        { id: 'brevets_deposes',  label: T.f_brev_dep,      type: 'number', required: false, min: 0 },
        { id: 'brevets_acceptes', label: T.f_brev_acc,      type: 'number', required: false, min: 0,
          validate: (v, form) => +v > +(form.brevets_deposes||999) ? T.err_brev_acc_gt_dep : null },
        { id: 'prototypes',       label: T.f_proto,         type: 'number', required: false, min: 0 },
        { id: 'trl',              label: T.f_trl,           type: 'select', required: false,
          options: ['N/A', 'TRL 1', 'TRL 2', 'TRL 3', 'TRL 4', 'TRL 5', 'TRL 6', 'TRL 7', 'TRL 8', 'TRL 9'] },
      ],
    },

    // ── SECTION 4 : FORMATION ─────────────────────────────────────────
    {
      id: 'formation',
      title: T.s_formation,
      icon: '🎓',
      color: '#5521B5',
      fields: [
        { id: 'h_initiale',  label: T.f_h_init,   type: 'number', required: true,  min: 0, max: 800, hint: T.hint_h_init },
        { id: 'h_executive', label: T.f_h_exec,   type: 'number', required: false, min: 0, max: 800 },
        { id: 'h_doctorale', label: T.f_h_doct,   type: 'number', required: false, min: 0, max: 800 },
        { id: 'doctorants',  label: T.f_doct,     type: 'number', required: true,  min: 0, max: 20 },
        { id: 'theses_sout', label: T.f_theses,   type: 'number', required: false, min: 0,
          validate: (v, form) => +v > +(form.doctorants||999) ? T.err_theses_gt_doct : null },
        { id: 'pfe',         label: T.f_pfe,      type: 'number', required: false, min: 0, max: 30 },
      ],
    },

    // ── SECTION 5 : PRESTATIONS DE SERVICE ───────────────────────────
    {
      id: 'prestations',
      title: T.s_prestations,
      icon: '💼',
      color: '#B45309',
      fields: [
        { id: 'nb_presta',   label: T.f_nb_prest,    type: 'number', required: false, min: 0 },
        { id: 'revenus_mad', label: T.f_revenus,     type: 'number', required: false, min: 0, hint: T.hint_mad },
        { id: 'type_presta', label: T.f_type_prest,  type: 'select', required: false,
          options: ['Aucune', 'Expertise technique', 'Audit / Diagnostic', 'Formation continue', 'Consulting', 'Étude de faisabilité', 'Autre'] },
        { id: 'role_prest',  label: T.f_role_prest,  type: 'select', required: false,
          options: ['Responsable (lead)', 'Co-responsable', 'Contributeur', 'Expert associé'] },
        { id: 'prest_detail',label: T.f_prest_detail,type: 'textarea', required: false,
          placeholder: T.ph_prest_detail },
      ],
    },

    // ── SECTION 6 : BILAN & COMMENTAIRES ─────────────────────────────
    {
      id: 'bilan',
      title: T.s_bilan,
      icon: '📋',
      color: '#BE123C',
      fields: [
        { id: 'statut_obj',    label: T.f_statut,     type: 'select',   required: true,
          options: [T.opt_atteint, T.opt_partiel, T.opt_non_atteint, T.opt_na] },
        { id: 'justif_ecarts', label: T.f_justif,     type: 'textarea', required: false,
          placeholder: T.ph_justif,
          hint: T.hint_justif },
        { id: 'faits_marq',    label: T.f_faits,      type: 'textarea', required: false, placeholder: T.ph_faits },
        { id: 'actions_corr',  label: T.f_actions,    type: 'textarea', required: false, placeholder: T.ph_actions },
        { id: 'besoins',       label: T.f_besoins,    type: 'textarea', required: false, placeholder: T.ph_besoins },
        { id: 'perspectives',  label: T.f_persp,      type: 'textarea', required: false, placeholder: T.ph_persp },
      ],
    },
  ]
}

export const ALL_FIELD_IDS = [
  'nom','email','grade','axe_recherche','annee_integ','orcid','scopus_url',
  'annee_academique','semestre_saisi',
  'prev_pub_total','prev_pub_q1q2','prev_citations','prev_projets_obt','prev_budget',
  'prev_conf_int','prev_brevets','prev_h_init','prev_h_exec','prev_h_doct',
  'prev_doctorants','prev_pfe','prev_prestations','prev_revenus','objectifs_texte',
  'pub_soumises','pub_acceptees','pub_q1q2','pub_final','citations','open_access',
  'type_oa','livres','doi_list','refs_biblio',
  'projets_soumis','projets_obtenus','budget_mad','projets_internat','financement',
  'role_projet','conferences_int','comm_invitees','brevets_deposes','brevets_acceptes',
  'prototypes','trl',
  'h_initiale','h_executive','h_doctorale','doctorants','theses_sout','pfe',
  'nb_presta','revenus_mad','type_presta','role_prest','prest_detail',
  'statut_obj','justif_ecarts','faits_marq','actions_corr','besoins','perspectives',
  'mode',
]

// ── Traductions ───────────────────────────────────────────────────────────
export const TRANSLATIONS = {
  fr: {
    // Modes
    mode_prevision:   '① Saisie des prévisions',
    mode_revision:    '② Révision S1 (mi-année)',
    mode_bilan:       '③ Bilan annuel',
    mode_hint_prev:   'Début d\'année académique — Définir vos objectifs annuels',
    mode_hint_rev:    'Après 6 mois — Réviser vos prévisions selon l\'avancement',
    mode_hint_bilan:  'Fin d\'année — Présenter vos réalisations et justifier les écarts',
    // Sections
    s_identification: 'Identification',
    s_previsions:     'Prévisions annuelles',
    s_production:     'Production scientifique',
    s_projets:        'Projets & Rayonnement',
    s_formation:      'Formation & Encadrement',
    s_prestations:    'Prestations de service',
    s_bilan:          'Bilan & Commentaires',
    // Fields
    f_nom:            'Nom complet',
    f_email:          'Email UM6P',
    f_grade:          'Grade académique',
    f_axe:            'Axe de recherche GSMI',
    f_annee_integ:    'Année d\'intégration UM6P',
    f_orcid:          'ORCID',
    f_scopus:         'Profil Scopus (URL)',
    f_annee_acad:     'Année académique',
    f_semestre:       'Semestre concerné',
    // Prévisions
    f_prev_pub:       'Objectif — Publications totales',
    f_prev_q1q2:      'Objectif — Publications Q1/Q2',
    f_prev_citations: 'Objectif — Citations',
    f_prev_projets:   'Objectif — Projets à obtenir',
    f_prev_budget:    'Objectif — Budget à obtenir (MAD)',
    f_prev_conf:      'Objectif — Conférences internationales',
    f_prev_brevets:   'Objectif — Brevets à déposer',
    f_prev_h_init:    'Objectif — H. Formation initiale',
    f_prev_h_exec:    'Objectif — H. Formation exécutive',
    f_prev_h_doct:    'Objectif — H. Formation doctorale',
    f_prev_doct:      'Objectif — Doctorants à encadrer',
    f_prev_pfe:       'Objectif — PFE / Masters à encadrer',
    f_prev_prest:     'Objectif — Nb. prestations de service',
    f_prev_revenus:   'Objectif — Revenus prestations (MAD)',
    f_objectifs_txt:  'Description des objectifs annuels',
    // Production
    f_pub_soumises:   'Publications soumises',
    f_pub_acceptees:  'Publications acceptées',
    f_pub_q1q2:       'Dont publications Q1/Q2',
    f_pub_final:      'Publications publiées (Final)',
    f_citations:      'Citations reçues (Scopus)',
    f_open_access:    'Publications Open Access',
    f_type_oa:        'Type d\'accès libre',
    f_livres:         'Livres & chapitres',
    f_doi_list:       'DOI des publications (vérification)',
    f_refs:           'Références bibliographiques complètes',
    // Projets
    f_proj_soumis:    'Projets soumis',
    f_proj_obtenus:   'Projets obtenus',
    f_budget:         'Budget total obtenu (MAD)',
    f_proj_internat:  'Projets internationaux',
    f_financement:    'Type de financement',
    f_role_projet:    'Rôle dans le(s) projet(s)',
    f_conf_int:       'Conférences internationales',
    f_comm_inv:       'Communications invitées',
    f_brev_dep:       'Brevets déposés',
    f_brev_acc:       'Brevets acceptés',
    f_proto:          'Prototypes / Transferts',
    f_trl:            'Niveau TRL',
    // Formation
    f_h_init:         'H. Formation initiale',
    f_h_exec:         'H. Formation exécutive',
    f_h_doct:         'H. Formation doctorale',
    f_doct:           'Doctorants encadrés (total en cours)',
    f_theses:         'Thèses soutenues ce semestre',
    f_pfe:            'PFE / Masters encadrés',
    // Prestations
    f_nb_prest:       'Nombre de prestations',
    f_revenus:        'Revenus générés (MAD)',
    f_type_prest:     'Type de prestation',
    f_role_prest:     'Rôle dans la prestation',
    f_prest_detail:   'Détail des prestations',
    // Bilan
    f_statut:         'Avez-vous atteint vos objectifs ?',
    f_justif:         'Justification des écarts (si ≥ 20%)',
    f_faits:          'Faits marquants',
    f_actions:        'Actions correctives prévues',
    f_besoins:        'Besoins de support',
    f_persp:          'Perspectives — prochain semestre',
    // Options
    opt_atteint:      'Oui, atteints ou dépassés',
    opt_partiel:      'Partiellement (75–99%)',
    opt_non_atteint:  'Non atteint (< 75%)',
    opt_na:           'Objectifs non définis',
    // Hints
    hint_orcid:       'Format : 0000-0000-0000-0000 — Vérification automatique du format',
    hint_annee_acad:  'Sélectionner l\'année académique concernée par cette saisie',
    hint_previsions:  'Ces objectifs seront comparés à vos réalisations en fin d\'année',
    hint_mad:         'Montant en dirhams marocains (MAD)',
    hint_pub_soumises:'Inclure tous les articles envoyés à des journaux / conférences',
    hint_doi:         'Saisir un DOI par ligne — Format : 10.XXXX/XXXXX — Vérification automatique',
    hint_refs:        'Auteurs, titre, journal, année, DOI — une publication par ligne',
    hint_h_init:      'Cours, TD, TP dispensés aux étudiants licence / master',
    hint_justif:      'Obligatoire si l\'écart dépasse 20% par rapport aux objectifs fixés',
    // Placeholders
    ph_objectifs:     'Décrire vos priorités et axes de travail pour cette année académique...',
    ph_refs:          'Ex: Alami M. et al. (2025). Titre article. Journal X, Vol. Y, pp. Z-Z. DOI: 10.XXXX/XX',
    ph_justif:        'Expliquer les raisons des écarts entre objectifs et réalisations...',
    ph_faits:         'Prix, collaborations nouvelles, événements marquants...',
    ph_actions:       'Mesures correctives pour le prochain semestre...',
    ph_besoins:       'Ressources, équipements, formations, partenariats souhaités...',
    ph_persp:         'Publications prévues, projets à soumettre, conférences planifiées...',
    ph_prest_detail:  'Décrire les missions réalisées, les clients, les livrables...',
    // Erreurs de validation
    err_email:        'Format email invalide',
    err_orcid:        'Format ORCID invalide (ex: 0000-0000-0000-0000)',
    err_q1q2_gt_total:'Les publications Q1/Q2 ne peuvent pas dépasser le total des publications',
    err_acc_gt_soum:  'Les publications acceptées ne peuvent pas dépasser les publications soumises',
    err_q1q2_gt_acc:  'Les publications Q1/Q2 ne peuvent pas dépasser les publications acceptées',
    err_oa_gt_acc:    'Les publications OA ne peuvent pas dépasser les publications acceptées',
    err_proj_gt_soum: 'Les projets obtenus ne peuvent pas dépasser les projets soumis',
    err_internat_gt_obt:'Les projets internationaux ne peuvent pas dépasser les projets obtenus',
    err_brev_acc_gt_dep:'Les brevets acceptés ne peuvent pas dépasser les brevets déposés',
    err_theses_gt_doct:'Les thèses soutenues ne peuvent pas dépasser le nombre de doctorants',
    err_doi_format:   'Format DOI invalide. Format attendu : 10.XXXX/XXXXX',
  },
  en: {
    mode_prevision:   '① Enter Forecasts',
    mode_revision:    '② Mid-Year Revision (S1)',
    mode_bilan:       '③ Annual Review',
    mode_hint_prev:   'Beginning of academic year — Set your annual targets',
    mode_hint_rev:    'After 6 months — Update your forecasts based on progress',
    mode_hint_bilan:  'End of year — Present achievements and justify variances',
    s_identification: 'Identification',
    s_previsions:     'Annual Forecasts',
    s_production:     'Scientific Output',
    s_projets:        'Projects & Outreach',
    s_formation:      'Teaching & Supervision',
    s_prestations:    'Service & Consultancy',
    s_bilan:          'Review & Comments',
    f_nom:            'Full name',
    f_email:          'UM6P email',
    f_grade:          'Academic grade',
    f_axe:            'GSMI research axis',
    f_annee_integ:    'UM6P integration year',
    f_orcid:          'ORCID',
    f_scopus:         'Scopus profile (URL)',
    f_annee_acad:     'Academic year',
    f_semestre:       'Semester',
    f_prev_pub:       'Target — Total publications',
    f_prev_q1q2:      'Target — Q1/Q2 publications',
    f_prev_citations: 'Target — Citations',
    f_prev_projets:   'Target — Projects to obtain',
    f_prev_budget:    'Target — Budget to obtain (MAD)',
    f_prev_conf:      'Target — International conferences',
    f_prev_brevets:   'Target — Patents to file',
    f_prev_h_init:    'Target — H. Initial training',
    f_prev_h_exec:    'Target — H. Executive training',
    f_prev_h_doct:    'Target — H. Doctoral training',
    f_prev_doct:      'Target — PhD students to supervise',
    f_prev_pfe:       'Target — PFE / Masters to supervise',
    f_prev_prest:     'Target — Nb. service contracts',
    f_prev_revenus:   'Target — Service revenue (MAD)',
    f_objectifs_txt:  'Annual objectives description',
    f_pub_soumises:   'Submitted publications',
    f_pub_acceptees:  'Accepted publications',
    f_pub_q1q2:       'Of which Q1/Q2',
    f_pub_final:      'Published (Final)',
    f_citations:      'Citations (Scopus)',
    f_open_access:    'Open Access publications',
    f_type_oa:        'Open Access type',
    f_livres:         'Books & chapters',
    f_doi_list:       'Publication DOIs (verification)',
    f_refs:           'Full bibliographic references',
    f_proj_soumis:    'Submitted projects',
    f_proj_obtenus:   'Obtained projects',
    f_budget:         'Total budget obtained (MAD)',
    f_proj_internat:  'International projects',
    f_financement:    'Funding type',
    f_role_projet:    'Role in project(s)',
    f_conf_int:       'International conferences',
    f_comm_inv:       'Invited communications',
    f_brev_dep:       'Patents filed',
    f_brev_acc:       'Patents granted',
    f_proto:          'Prototypes / Tech transfers',
    f_trl:            'TRL level',
    f_h_init:         'H. Initial training',
    f_h_exec:         'H. Executive training',
    f_h_doct:         'H. Doctoral training',
    f_doct:           'PhD students supervised (total)',
    f_theses:         'Theses defended this semester',
    f_pfe:            'PFE / Masters supervised',
    f_nb_prest:       'Number of contracts',
    f_revenus:        'Revenue generated (MAD)',
    f_type_prest:     'Contract type',
    f_role_prest:     'Role',
    f_prest_detail:   'Contract details',
    f_statut:         'Did you achieve your objectives?',
    f_justif:         'Justification of variances (if ≥ 20%)',
    f_faits:          'Key highlights',
    f_actions:        'Corrective actions planned',
    f_besoins:        'Support needs',
    f_persp:          'Outlook — next semester',
    opt_atteint:      'Yes, achieved or exceeded',
    opt_partiel:      'Partially (75–99%)',
    opt_non_atteint:  'Not achieved (< 75%)',
    opt_na:           'Objectives not defined',
    hint_orcid:       'Format: 0000-0000-0000-0000 — Automatic format check',
    hint_annee_acad:  'Select the academic year for this submission',
    hint_previsions:  'These targets will be compared to your achievements at year end',
    hint_mad:         'Amount in Moroccan Dirhams (MAD)',
    hint_pub_soumises:'Include all articles sent to journals / conferences',
    hint_doi:         'Enter one DOI per line — Format: 10.XXXX/XXXXX — Auto-verified',
    hint_refs:        'Authors, title, journal, year, DOI — one publication per line',
    hint_h_init:      'Courses, tutorials, labs delivered to bachelor / master students',
    hint_justif:      'Required if variance exceeds 20% vs. set objectives',
    ph_objectifs:     'Describe your priorities and focus areas for this academic year...',
    ph_refs:          'Ex: Alami M. et al. (2025). Article title. Journal X, Vol. Y, pp. Z-Z. DOI: 10.XXXX/XX',
    ph_justif:        'Explain the reasons for variances between targets and achievements...',
    ph_faits:         'Awards, new collaborations, key events...',
    ph_actions:       'Corrective measures for next semester...',
    ph_besoins:       'Resources, equipment, training, partnerships needed...',
    ph_persp:         'Planned publications, projects to submit, conferences...',
    ph_prest_detail:  'Describe missions completed, clients, deliverables...',
    err_email:        'Invalid email format',
    err_orcid:        'Invalid ORCID format (e.g. 0000-0000-0000-0000)',
    err_q1q2_gt_total:'Q1/Q2 publications cannot exceed total publications',
    err_acc_gt_soum:  'Accepted publications cannot exceed submitted publications',
    err_q1q2_gt_acc:  'Q1/Q2 publications cannot exceed accepted publications',
    err_oa_gt_acc:    'OA publications cannot exceed accepted publications',
    err_proj_gt_soum: 'Obtained projects cannot exceed submitted projects',
    err_internat_gt_obt:'International projects cannot exceed obtained projects',
    err_brev_acc_gt_dep:'Granted patents cannot exceed filed patents',
    err_theses_gt_doct:'Defended theses cannot exceed number of PhD students',
    err_doi_format:   'Invalid DOI format. Expected: 10.XXXX/XXXXX',
  },
}
